set DATEFIRST 1;
SELECT TEAM, SUM(POINTS) Total_Points
INTO #TEAMS
FROM EMPLOYEES
WHERE DATES
BETWEEN DATEADD(Day, 1-DATEPART(WEEKDAY,GETDATE())-7, DATEDIFF(Day, 0, GetDate())) 
AND DATEADD(Day, -DATEPART(WEEKDAY,GETDATE()), DATEDIFF(Day, 0, GetDate())) 
GROUP BY TEAM
ORDER BY Total_Points DESC;
SELECT Top 1 TEAM FROM #TEAMS;
DROP TABLE #TEAMS;
